name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure for release
      run: cd bochs && ./.conf.linux
    - name: make
      run: make
    - name: clean
      run: make clean
    - name: configure minimalistic configuration
      run: cd bochs && ./.conf.nothing
    - name: make
      run: make
    
